[package]
name = "cars-decomp"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5"
texpresso = "2"
image = "0.25"
walkdir = "2.5"
sha256 = "1"
alphanumeric-sort = "1.5"
audio-codec-algorithms = "0.7"